= Asset Extraction

In _Asset Extraction_ you need to extract an _Asset_ (undercover agent).

*Type:* Solo, Coop, PvE.

*Players:* 1-8.

== Objectives

* Protect the Asset.
* Avoid collateral damage. (Only in _Semi-Permissive_ variant)
* Extract via exfil point.

Variations:

[arabic]
. _Asset Extraction_: Everyone is a combatant.
. _Asset Extraction (Semi-Permissive)_: Combatant and non-combatants are present.
  Combatants are wearing balaclavas and chest rigs.
. _Asset Extraction (Semi-Permissive, LowViz)_: Combatant and non-combatants are present.
  Combatants are using low visibility gear.

== Game play

[arabic]
. One player selects the "`__Asset__ (0/1)`" insertion point. All other players select a regular insertion point.
. Team and _Asset_ go to exfil point
. The _Asset_ needs to survive.

*Note:* If no player has selected the "`__Asset__ (0/1)`" insertion point, a random player will be made the _Asset_. (Players that have not selected an insertion point take precedence.)

== Settings

* *Expected resistance* - impacts the amount of enemies that will spawn in mission.
  The final Opposing Force count takes player count and this setting into account.

== Additional notes

The _Asset_ might want to dress up in OPFOR clothing.

== Admin console commands

Open the console via kbd:[F7] or kbd:[+*+] (Num Pad). On US keyboards you can also use kbd:[+~+].

Type:

`admin reloadmissionscript loc=<NUMBER>`::
  Select Asset spawn location.
  Will not be visible on OPS board.
  Use `+0+` for random.
`+admin reloadmissionscript help+`::
  Display help text.
`+admin reloadmissionscript rand+`::
`+admin reloadmissionscript rand obj+`::
  Randomize objectives.
`+admin reloadmissionscript rand exfil+`::
  Pick a new random exfil point.

*Note:* In single player mode type "```debuggamecommand```" instead of "```admin```".
