= Mission Editing Guide

== Basics

. Visit the "`#gb-modding`" channel in the https://discord.com/invite/9pp3TrT[official GROUND BRANCH Discord]. The mission editor guide can be found in the pinned posts.
. This video playlist provides an introduction to the editor: https://www.youtube.com/playlist?list=PLle5osICJhZJwHxGOb1iBXoyu_uk9yXMY.
. For each mission type we need AI spawns. The "`AI priority`" field is not used, instead we add a "`Group<N>`" tag, where _N_ is a natural number greater-than 1.
. For each mission type we need insertion points and extraction points.

== Suggested order

. Create "`Kill Confirmed`"
. Create "`Break Out`" based on "`Kill Confirmed`".
. Create "`Kill Confirmed (Semi-Permissive, LowViz)`" based on "`Kill Confirmed`".
. Generate "`Kill Confirmed (Semi-Permissive)`" via script.
. Create "`Security Detail (Semi-Permissive, LowViz)`" and "`Asset Extraction (Semi-Permissive, LowViz)`" based on "`Kill Confirmed (Semi-Permissive, LowViz)`".
. Generate "`Security Detail/Asset Extraction (Semi-Permissive)`" via script.
. Create "`Security Detail`" and "`Asset Extraction`" based on the "`(Semi-Permissive, LowViz)`" variants.

== Mission-type specific notes

=== Kill Confirmed

* Add hostile AI spawn points with "`Group`" tags. Using the kits from "`EurAsi`" or "`MidEas`".
* Add HVT AI spawns tagged as "`HVT`". Using the “HVT_*” kits from "`EurAsi`" or "`MidEas`".

=== Kill Confirmed (Semi-Permissive, LowViz)

Start with a copy of "`Kill Confirmed`".

* Change the kits from "`EurAsi`"/"`MidEas`" to "`Narcos`" kits.
* Add non-combatants with team ID "`10`" and "`Narcos/Civ<1-8>`" kit.

=== Kill Confirmed (Semi-Permissive)

This variant is generated via the script "`ReplaceLowVizKitsInMis.sed`".

=== Break Out

Start with a copy of "`Kill Confirmed`".

* Remove all insertion points. Add a new insertion point called "`Prison`".
* Remove all HVT spawns.
* Add additional patrols and guards.

=== Security Detail (Semi-Permissive, LowViz)

. It can make sense to start from a "`Kill Confirmed (Semi-Permissive, LowViz)`" mission.
+
For the following we will assume that we are editing "`Small Town`" with the following well-known (from "`Intel Retrieval`") InsertionPoint and ExtractionPoints:
* InsertionPoint: North-East, South-East, South-West
* ExtractionPoint: NE,SE,SW (near respective Spawn point); NWGate (Extraction behind Building A)
+
Let us assume that we want to add the following VIP InsertionPoints:
* VIP-North-East, VIP-South-East, VIP-South-West
* VIP-In-Building-B, VIP-In-Building-D
* VIP-In-Building-A (this one is just used in this text and not in the actual mission)
. Understanding escape routes
+
Some game modes pick a random ExtractionPoint indiscriminately. This would not work well for "`Security Detail`": For example for VIP-In-Building-A the ExtractionPoint NWGate (Extraction behind Building A) would be too easy to reach (it is too close, and you can use building A as partial cover).
+
Therefore, we use a different strategy: You, as a mission maker, define which escape routes are allowed. This is done by linking the VIP InsertionPoints to ExtractionPoints via tags.
. Tagging ExtractionPoints
+
Each ExtractionPoint MUST have at least one tag in the form of "`Exfil-TXT`" (where TXT is some text). Multiple tags are allowed.
+
For example, we could tag:
* NE with "`Exfil-NE`" and "`Exfil-East`"
* SE with "`Exfil-SE`" and "`Exfil-East`"
* SW with "`Exfil-SW`" and "`Exfil-West`"
* NWGate with "`Exfil-NW`" and "`Exfil-West`"
. Tagging PSD (personal security detail) InsertionPoints
+
Each non-VIP InsertionPoint MUST have at EXACTLY one tag in the form of "`IP-TXT`" (where TXT is some text). For example, we could tag InsertionPoint South-West with "`IP-SW`".
. Adding VIP InsertionPoints for "`Travel`" scenario
+
In the escort scenario we escort the VIP from one edge of the map to another. In this example we will create VIP-South-West:
.. Create an InsertionPoint The name of the InsertionPoint is functionally irrelevant, however we suggest that you use something like "`VIP:South-West`".
.. Add tag "`VIP-Travel`" and set the team ID to 1.
.. Add PlayerStarts to the InsertionPoint via Editor button. Note that there must be _exactly_ one PlayerStart per VIP InsertionPoint. (Delete 7 of the 8 PlayerStarts.)
.. Link the VIP to his extractions: Add one or more Exfil tags to the VIP InsertionPoint.
.. Link the VIP to his PSD: Add the tag "`IP-SW`" to the VIP InsertionPoint. Note: When the "`Available Forces`" OPS board setting is set to "`PSD only`", only InsertionPoints linked to the VIP InsertionPoint (via tag) will be enabled.
. Adding VIP InsertionPoints for "`Exfil`" scenario
+
In the exfil scenario we escort the VIP from the inside of the map to an edge of the map.
.. Create an InsertionPoint (same as 4.1)
.. Add tag "`VIP-Exfil`" and set the team ID to 1.
.. Add PlayerStarts via Editor button. (same as 4.3)
.. Link the VIP to his extractions (same as 4.4)
.. Create PSD InsertionPoint: Add an InsertionPoint with team ID 1. Use a name like "`Building-B`". Add the tag "`Hidden`", and a tag like "`IP-B`" to the InsertionPoint.
.. Link the VIP to his PSD: Add the tag "`IP-B`" to the VIP InsertionPoint. When the "`Available Forces`" OPS board setting is set to "`PSD only`", only InsertionPoints linked to the VIP InsertionPoint (via tag) will be enabled.
.. Create PSD PlayerStarts Create 7 (or 8) PlayerStarts Move the VIP PlayerStart so that the VIP is covered by his PSD.
. Creating "`Restricted`" InsertionPoints
+
By default, the script will put late comers (players that have not selected an InsertionPoint) to the VIP’s PSD.
+
For some PSD InsertionPoints you might not have enough space to place 7 PlayerStarts. In such cases tag the InsertionPoint with "`Restricted`" so that script will not use that InsertionPoint for late comers.
. Testing
.. If you run "`Validate`" in the mission editor the script will print all escape routes into the GB Log file.
.. Individual Insertion Points can be activated on the OPS board via console command "`DebugGameCommand reloadmissionscript loc=2`".

=== Asset Extraction (Semi-Permissive, LowViz)

The "`Asset Extraction (Semi-Permissive, LowViz)`" mission is the same as "`Secuirty Detail (Semi-Permissive, LowViz)`", with the following tweaks added:

* Add an InsertionPoint with tag "`Asset`"
* Add PlayerStarts to InsertionPoint via Editor button. Note that there must be _exactly_ one PlayerStart. (Delete 7 of the 8 PlayerStarts).
* Add orphaned (Group=None) PlayerStarts with tag "`Asset`"

=== Security Detail (Semi-Permissive)

This variant is generated via the script "`ReplaceLowVizKitsInMis.sed`".

=== Asset Extraction (Semi-Permissive)

This variant is generated via the script "`ReplaceLowVizKitsInMis.sed`".

=== Security Detail/Asset Extraction

* Copy "`Security Detail/Asset Extraction (Semi-Permissive, LowViz)`"
* Replace all non-combatants AI (AI with team ID 10) kits with different “Nacro/*” kits and change the team ID to 100.


== Kit notes

Here's a list of included kits that can be used:

* EurAsi/HVT_AR_BLACK
* EurAsi/HVT_CQB_BLACK
* EurAsi/HVT_SNP_BLACK
* EurAsi/HVT_STG_BLACK
* EurAsi/SO_AR
* EurAsi/SO_CQB
* EurAsi/SO_HVT_AR
* EurAsi/SO_HVT_CQB
* EurAsi/SO_HVT_SNP
* EurAsi/SO_HVT_STG
* EurAsi/SO_LMG
* EurAsi/SO_SNP
* EurAsi/SO_STG

* MidEas/HVT_AR
* MidEas/HVT_CQB
* MidEas/HVT_HDG
* MidEas/HVT_SNP
* MidEas/HVT_STG
* MidEas/SO_AR
* MidEas/SO_CQB
* MidEas/SO_LMG
* MidEas/SO_SNP
* MidEas/SO_STG
* MidEas/STD_AR
* MidEas/STD_CQB
* MidEas/STD_LMG
* MidEas/STD_SNP
* MidEas/STD_STG

* Narcos/Civ1-8
* Narcos/HVT_AR1-2
* Narcos/Param_AR1-2
* Narcos/Param_LMG1-2
* Narcos/Param_SMG1-2
* Narcos/Param_SNP1-2
* Narcos/Param_STG1-2
* Narcos/Tango_AR1-8
* Narcos/Tango_HDG1-8
* Narcos/Tango_LMG1-8
* Narcos/Tango_SMG1-8
* Narcos/Tango_SNP1-8
* Narcos/Tango_STG1-8

=== Handguns

In GROUND BRANCH v1034, AI can not use handguns. As a workaround handguns where replaced with "`BP_MP5A5`".
